# Generated by Django 5.1.7 on 2026-04-14 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age_user_current_status_user_education_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='industries',
        ),
        migrations.RemoveField(
            model_name='user',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='open_to_learning',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_style',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_type',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(blank=True, choices=[('Student', 'Student'), ('Professional', 'Professional')], max_length=20, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_projects', models.TextField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('career_goal', models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('Data Science', 'Data Science'), ('AI/ML', 'AI/ML')], max_length=50, null=True)),
                ('timeline', models.CharField(blank=True, choices=[('3 months', '3 months'), ('6 months', '6 months'), ('1 year', '1 year')], max_length=20, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('Job', 'Job'), ('Internship', 'Internship'), ('Freelancing', 'Freelancing'), ('Startup', 'Startup')], max_length=20, null=True)),
                ('hours_per_day', models.CharField(blank=True, choices=[('<1', '<1'), ('1–2', '1–2'), ('3–5', '3–5'), ('5+', '5+')], max_length=10, null=True)),
                ('learning_style', models.CharField(blank=True, choices=[('Video', 'Video'), ('Reading', 'Reading'), ('Practice', 'Practice'), ('Mixed', 'Mixed')], max_length=20, null=True)),
                ('confidence_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_area', models.CharField(choices=[('UI/UX', 'UI/UX'), ('Problem Solving', 'Problem Solving'), ('Projects', 'Projects'), ('AI/ML', 'AI/ML'), ('Data', 'Data'), ('Backend', 'Backend')], max_length=50)),
                ('preferred_method', models.CharField(choices=[('Projects', 'Projects'), ('Tutorials', 'Tutorials'), ('Coding Problems', 'Coding Problems'), ('Reading', 'Reading')], max_length=50)),
                ('confidence_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(choices=[('lack of direction', 'lack of direction'), ('inconsistency', 'inconsistency'), ('too many resources', 'too many resources'), ('lack of practice', 'lack of practice'), ('forgetting concepts', 'forgetting concepts')], max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_day', models.CharField(blank=True, choices=[('<1', '<1'), ('1–2', '1–2'), ('3–5', '3–5'), ('5+', '5+')], max_length=10, null=True)),
                ('learning_style', models.CharField(blank=True, choices=[('Video', 'Video'), ('Reading', 'Reading'), ('Practice', 'Practice'), ('Mixed', 'Mixed')], max_length=20, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_preferences', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IkigaiScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_score', models.FloatField(default=0)),
                ('backend_score', models.FloatField(default=0)),
                ('fullstack_score', models.FloatField(default=0)),
                ('data_science_score', models.FloatField(default=0)),
                ('ai_ml_score', models.FloatField(default=0)),
                ('best_fit', models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('Data Science', 'Data Science'), ('AI/ML', 'AI/ML')], max_length=50)),
                ('result_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ikigai_score', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IkigaiResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passion', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('impact', models.JSONField(blank=True, default=list)),
                ('career', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ikigai_response', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_goal', models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('Data Science', 'Data Science'), ('AI/ML', 'AI/ML')], max_length=50, null=True)),
                ('timeline', models.CharField(blank=True, choices=[('3 months', '3 months'), ('6 months', '6 months'), ('1 year', '1 year')], max_length=20, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('Job', 'Job'), ('Internship', 'Internship'), ('Freelancing', 'Freelancing'), ('Startup', 'Startup')], max_length=20, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='accounts.userprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.skill')),
            ],
            options={
                'unique_together': {('profile', 'skill')},
            },
        ),
    ]
