# Generated by Django 6.0.2 on 2026-05-27 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skill_remove_user_age_remove_user_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='interest_area',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Data Science', 'Data Science'), ('Cybersecurity', 'Cybersecurity'), ('UI/UX Design', 'UI/UX Design'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Teaching', 'Teaching'), ('Law', 'Law'), ('Content Creation', 'Content Creation'), ('Entrepreneurship', 'Entrepreneurship'), ('Research', 'Research')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='career_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CareerQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_career', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField(default=0)),
                ('career_category', models.CharField(blank=True, max_length=100, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_results', to='accounts.userprofile')),
            ],
        ),
    ]
